<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\EntityRepository;
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllUser()
    {
      return $this->createQueryBuilder('user')
          ->select('user.nama', 'user.alamat', 'user.email')
          ->getQuery()
          ->getResult();
    }

    public function findUserByUserId($id){
        return $this->createQueryBuilder('user')
            ->select('user.nama', 'user.alamat', 'user.email')
            ->andWhere('user.id == :id')
            ->setParameter('id','1')
            ->getQuery()
            ->getOneOrNullResult()
    }
}
